<?php

/**
 * @file
 * Contains maria_layout_overrides.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

 /**
 * Implements hook_help().
 */
function maria_database_connection_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      // Main module help for the maria_database_connection module.
      case 'help.page.maria_database_connection':
        $output = '';
        $output .= '<h3>' . t('About') . '</h3>';
        $output .= '<p>' . t('Fondo Maria M3 database case register methods and tools.') . '</p>';
        return $output;
  
      default:
    }
  }

function maria_database_connection_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'webform_submission_direct_attention_form_add_form') {
    module_load_include('inc', 'maria_database_connection', 'includes/fondomariadb_api_integration');
    $api_config = fondomariadb_get_api_configuration();

    if($api_config) {
      $form['#api'] = $api_config;
      // $form['actions']['submit']['#submit'][] = 'maria_database_connection_form_handler';
    }
  }
}

function maria_database_connection_form_handler($form, &$form_state) {
  module_load_include('inc', 'maria_database_connection', 'includes/fondomariadb_api_integration');
  fondomariadb_send_data($form, $form_state);
}