<?php

/**
 * @file
 * Contains maria_layout_overrides.module.
 */

 /**
 * Implements hook_help().
 */
function maria_database_connection_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      // Main module help for the maria_database_connection module.
      case 'help.page.maria_database_connection':
        $output = '';
        $output .= '<h3>' . t('About') . '</h3>';
        $output .= '<p>' . t('Fondo Maria M3 database case register methods and tools.') . '</p>';
        return $output;
  
      default:
    }
  }

function maria_database_connection_form_alter(&$form, &$form_state, $form_id) {
    // Aim here to the newly created webform and attach the case register method from the include
    module_load_include('inc', 'maria_database_connection', 'includes/fondomariadb_api_integration');

    $isApiConfigured = fondomariadb_check_api_configuration();
}