#!/bin/bash

ddev composer install
ddev compile-dev-theme
ddev drush site-install --site-name=${DDEV_PROJECT} --account-name=admin --account-pass=admin --account-mail=web-admin@matrushka.com.mx --site-mail=web-admin@matrushka.com.mx --yes