#!/bin/bash

ddev drush site-install --site-name=${DDEV_PROJECT} --account-name=admin --account-mail=web-admin@matrushka.com.mx --site-mail=web-admin@matrushka.com.mx --yes
ddev drush theme:enable m3_custom_theme
ddev drush config-set system.theme default m3_custom_theme --yes
